dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: mysql
  version: 1.6.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
